#pragma once
#include <tavoos/widget/templates/control.h>
#include <tavoos/widget/templates/buttonbase.h>
#include <tavoos/widget/templates/buttongroup.h>
#include <tavoos/widget/templates/progressbarbase.h>
#include <tavoos/widget/templates/rangebase.h>
#include <tavoos/widget/templates/sliderbase.h>
#include <tavoos/widget/templates/spinboxbase.h>
#include <tavoos/widget/templates/textfieldbase.h>
