file(READ "${INPUT_FILE}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LENGTH)
math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")
string(REGEX REPLACE "(..)" "0x\\1," HEX_ARRAY "${HEX_CONTENT}")

file(WRITE "${OUTPUT_FILE}" "// Auto-generated by tavoos_add_resource — do not edit.
#include <tavoos/resources/resourceregistry.h>
namespace {
static const unsigned char res_data_${SYMBOL}[] = { ${HEX_ARRAY} };
struct Registrar_${SYMBOL} {
    Registrar_${SYMBOL}() {
        Tavoos::ResourceRegistry::registerResource(\"${RESOURCE_PATH}\", res_data_${SYMBOL}, ${BYTE_COUNT});
    }
} registrar_${SYMBOL};
}
")
