set(CPACK_PACKAGE_NAME "tavoos")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VENDOR "AmirHosseinCH")
set(CPACK_PACKAGE_CONTACT "AmirHosseinCH <amirhosseinchoghaei@gmail.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_DESCRIPTION}")

set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SECTION "libdevel")

set(CPACK_DEBIAN_PACKAGE_NAME "libtavoos-dev")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libglm-dev, libfreetype-dev")

include(CPack)
